version: "3.9"

services:
  java:
    image: openjdk:8
    container_name: "dockerDB"
    restart: always
    ports:
      - 8091:8091
    volumes:
      - .:/home
    environment:
      cntStr: jdbc:postgresql://10.151.128.191/company?user=postgres&password=fred&currentSchema=staff
    entrypoint: java -jar /home/docker1-1.0.0.jar -i -cp "/home/staff.csv" -tn "employee" -cn "id, name, gender, department, email, salary"

#  writeCSV
#  entrypoint: java -jar /home/docker1-1.0.0.jar -w -cp "/home/staff.csv" -ss "select * from staff.employee"
