version: "3.9"

services:
  db:
    image: postgres:alpine
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5000:5000
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fred
      POSTGRES_DB: company



